In [2]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [ ]:
"""
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables.
"""

In [ ]:
#Ans 1:
"""
The difference is type of list_ is a list(It can store values of different data types) and array_list is an array(It can store values of 
same data type).

In [4]:
type(list_)

list

In [5]:
type(array_list)

numpy.ndarray

In [ ]:
"""
Q2. Write a code to print the data type of each and every element of both the variables list_ and 
array_list.
"""

In [ ]:
#Ans 2:

In [6]:
type(list_)

list

In [7]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [8]:
type(array_list)

numpy.ndarray

In [9]:
for j in array_list:
    print(type(j))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
"""
Q3.Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list.
"""

In [10]:
array_list = np.array(object = list_, dtype = int)

In [11]:
array_list

array([1, 2, 3, 4, 5])

In [ ]:
"""
The data type will change from string to integer
"""

In [12]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [13]:
for j in array_list:
    print(type(j))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [14]:
import numpy as mp

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [ ]:
"""
Q4. Write a code to find the following characteristics of variable, num_array:
1. shape
2. size
"""

In [ ]:
#Ans 4:
"""
1. Shape gives the number of rows and column as (row,column)

2. Size gives the number of elements in the array
"""

In [15]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
num_array.size

6

In [17]:
num_array.shape

(2, 3)

In [ ]:
"""
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.
"""

In [22]:
#Ans 5
import numpy as np

In [25]:
def np_func(a,b):
    arr = np.zeros((a,b), dtype='int')
    return arr

In [26]:
np_func(3,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
"""
Q6. Create an identity matrix of shape (5,5) using numpy functions?
"""

In [20]:
arr = np.eye(5, dtype='int')

In [21]:
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])